import json


# Get name and year

with open('name_year','r') as g:
    result = g.readline()
    

# result = list(result)
print("resulte" , result )
name_and_year = result

name_and_year = name_and_year.split(" - ")
print(name_and_year)

name = name_and_year[1]
year = name_and_year[0]

name = name.strip()
# year = year.replace(".XLSX","")
year = year.strip()
print("Year: "+ year, "Name: " + name)




# Open the data generated by Camelot and make the name as the head of the json file
with open('foo.json') as d:
        userdata = json.load(d)
        # name  = "Kojo"
        new_userdata = {name: userdata}
        # Serializing json
        user_data = json.dumps(new_userdata, indent=4)

# Write this new name and replace an old one
with open('single_user_data.json', 'w') as outfile:

    outfile.write(user_data)

# Now read this into a var named user?
with open("single_user_data.json", "r") as json_file:

    user = json.load(json_file)
    # year = "DP2"

# day = 1
# period = '4'
# print(user['STUDENTS']['ABdul-mubs'][1][period])

    # with open('final_testNew.json', 'r+') as jfile:
    #     j = json.load(jfile)
    #     user_data['STUDENTS'] = userdata
    #     jfile.seek(0)
    #     json.dump(j, jfile, indent=4)
    # with open('final_testNew.json', 'r') as f:
    #     json_data = json.load(f)
    #     print( json_data.values() )# View Previous entries)
    #     json_data.update(user_data)

    # Unnamed: 0

    
# Now add it to the final file.json and add year group
    ########## Update STUDENTS #############
with open('file.json', 'r+') as file:
    data = json.load(file)
    data['STUDENTS'].update(user)
    data['STUDENTS'][name][0]['0'] = year
    file.seek(0)
    json.dump(data, file, indent=4)


