
classroom_fullname = {
    "MUSR":"MUSIC ROOM",
    "AVR1":"AUDIO VISUAL ROOM ONE",
    "AVR2":"AUDIO VISUAL ROOM TWO",
    "ER1":"ENGLISH ROOM ONE",
    "ER2":"ENGLISH ROOM TWO",
    "ER3":"ENGLISH ROOM THREE",
    "ER4":"ENGLISH ROOM FOUR",
    "MR1":"MATH ROOM ONE",
    "MR2":"MATH ROOM TWO",
    "MR3":"MATH ROOM THREE",
    "MR4":"MATH ROOM FOUR",
    "HR1":"HUMANITIES ROOM ONE",
    "HR2":"HUMANITIES ROOM TWO",
    "HR3":"HUMANITIES ROOM THREE",
    "MLR1":"MODERN LANGUAGES ROOM ONE",
    "MLR1":"MODERN LANGUAGES ROOM TWO",
    "MLR1":"MODERN LANGUAGES ROOM THREE",
    "MLR1":"MODERN LANGUAGES ROOM FOUR",
    "AR":"ART ROOM",
    "ITL1":"IT LAB ONE",
    "ITL2":"IT LAB TWO",
    "MS":"MARKERS SPACE",
    "GR":"GENERAL ROOM",
    "GL":"GENERAL LAB",
    "CL":"CHEMISTRY LAB",
    "BL":"BIOLOGY LAB",
    "PL":"PHYSICS LAB",
    "ML":"MAC LAB",
    "MNH":"MAGARET NKRUMAH HALL",
}

teachers = 'JA-MT ','NAA ','AK ','CA ','HAM ','DA ','RH ','MD ','TO ','VE ','EAA ','SM ','NM ','JA ','EFV ','EE ','JK ','MC','MO ','ECT ','DS ','IS ','ED ','MT ','LS', 'SE ', 'EE-LEK ', 'REN-BAA-KA ', 'MT-EE ', 'KAD ',  'KB ', 'ABM ', 'SK ', 'DS ', 'GA ', 'MG ', 'SM ', 'EG', 'SC ', 'AAS ', 'JB ', 'PK ', 'LEK ','KA ','BAA ','REN ','GGH'


teachers_fullname = {
    "JA":"Jonathan Amenghor/Malik Torbay",
    "NAA":"Neo Ankamah-Asamoah",
    "AK":"Ami Kodjovi",
    "CA":"Charles Antwi",
    "DA":"Dela Avemega",
    "MC":"Mark Carter",
    "RH":"Robert Hormeku",
    "MD":"Michael Djan",
    "TO":"Timothy Obuobi",
    "VE":"Vivian Essuman",
    "EAA":"Enoch Augustine Acquah",
    "NM":"Napoleon",
    "JA":"Jonathan Amenghor",
    "EFV":"Etornam Fianoo Vidza",
    "EE":"MRS Eyiah",
    "JK":"John Kamau",
    "HAM":"Hubert Asiedu Mante",
    "MO":"Michael Oduro",
    "PH":"Prosper Habada",
    "ECT":"Clemence Tengey",
    "DS":"Deborah Sampson",
    "ED":"Enyonam Dzide",
    "KB": "Kwaku Boateng",
    "AAS": "Afua Addae Sakyi",
    "GGH": "George Hallow Grandy",
    "ABM": "Andrews Boadi-Manu",
    "KAD": "Kingsley Adi-Darko",
    "AAS": "Afua Addae Sakyi",
    "AAS": "Afua Addae Sakyi",

}